"""Base template class for project generation"""
from pathlib import Path
from typing import List, Optional


class ProjectTemplate:
    """Base class for project templates"""
    
    # Template metadata (to be overridden by subclasses)
    name: str = "Base Template"
    description: str = "Base project template"
    
    def __init__(self, project_name: str, project_path: Path):
        self.project_name = project_name
        self.project_path = project_path
        self.common_folders = [
            "notebooks",
            "artifacts/wip",
            "artifacts/completed",
            "reports",
            "research",
            "quality",
            "scripts",
            "data",
            "tests"
        ]
    
    def create_folder_structure(self, additional_folders: Optional[List[str]] = None):
        """Create common folder structure"""
        folders = self.common_folders + (additional_folders or [])
        for folder in folders:
            (self.project_path / folder).mkdir(parents=True, exist_ok=True)
            # Add .gitkeep files
            (self.project_path / folder / ".gitkeep").touch()
    
    def create_pyproject_toml(self, dependencies: List[str]):
        """Create pyproject.toml for uv"""
        # Format dependencies as a proper list without extra quotes
        deps_formatted = ",\n    ".join(dependencies)
        
        content = f'''[project]
name = "{self.project_name}"
version = "0.1.0"
description = "A Python project generated by project-generator"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    {deps_formatted}
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src"]

[dependency-groups]
dev = [
    "pytest>=7.4.0",
    "pytest-cov>=4.1.0",
    "black>=23.7.0",
    "ruff>=0.0.285",
    "ipykernel>=7.1.0",
]
'''
        with open(self.project_path / "pyproject.toml", "w") as f:
            f.write(content)
    
    def create_gitignore(self):
        """Create .gitignore file"""
        content = '''# Python
__pycache__/
*.py[cod]
*$py.class
*.so
.Python
env/
venv/
.venv/
ENV/
build/
develop-eggs/
dist/
downloads/
eggs/
.eggs/
lib/
lib64/
parts/
sdist/
var/
wheels/
*.egg-info/
.installed.cfg
*.egg

# Testing
.pytest_cache/
.coverage
htmlcov/

# IDEs
.vscode/
.idea/
*.swp
*.swo
*~

# Data
data/raw/*
data/processed/*
!data/raw/.gitkeep
!data/processed/.gitkeep

# Notebooks
.ipynb_checkpoints/

# Environment
.env
.env.local

# OS
.DS_Store
Thumbs.db
'''
        with open(self.project_path / ".gitignore", "w") as f:
            f.write(content)
    
    def create_readme(self, content: str):
        """Create README.md"""
        with open(self.project_path / "README.md", "w") as f:
            f.write(content)
    
    def create_basic_test(self):
        """Create a basic test file"""
        content = '''"""Basic tests for the project"""
import pytest


def test_project_structure():
    """Test that project structure is correct"""
    import os
    from pathlib import Path
    
    project_root = Path(__file__).parent.parent
    expected_dirs = ["notebooks", "artifacts", "reports", "research", "quality", "scripts", "data"]
    
    for dir_name in expected_dirs:
        assert (project_root / dir_name).exists(), f"Missing directory: {dir_name}"


def test_placeholder():
    """Placeholder test"""
    assert True
'''
        with open(self.project_path / "tests" / "test_basic.py", "w") as f:
            f.write(content)
        
        # Create __init__.py
        (self.project_path / "tests" / "__init__.py").touch()
    
    def create_src_init(self):
        """Create src/__init__.py to make it a proper package"""
        (self.project_path / "src" / "__init__.py").write_text(
            f'"""{self.project_name} package."""\n'
        )
    
    def generate(self):
        """Generate the project (to be implemented by subclasses)"""
        raise NotImplementedError("Subclasses must implement generate()")

