"""Base template class for project generation"""
from pathlib import Path
from typing import List, Optional
from ..constants import COMMON_FOLDERS, DEV_DEPENDENCIES, PYTHON_VERSION, BUILD_SYSTEM


class ProjectTemplate:
    """Base class for project templates"""
    
    # Template metadata (to be overridden by subclasses)
    name: str = "Base Template"
    description: str = "Base project template"
    
    def __init__(self, project_name: str, project_path: Path):
        self.project_name = project_name
        self.project_path = project_path
        self.common_folders = COMMON_FOLDERS.copy()
    
    def create_folder_structure(self, additional_folders: Optional[List[str]] = None):
        """Create common folder structure"""
        try:
            folders = self.common_folders + (additional_folders or [])
            for folder in folders:
                folder_path = self.project_path / folder
                folder_path.mkdir(parents=True, exist_ok=True)
                # Add .gitkeep files
                (folder_path / ".gitkeep").touch()
        except (OSError, PermissionError) as e:
            raise RuntimeError(f"Failed to create folder structure: {e}") from e
    
    def create_pyproject_toml(self, dependencies: List[str]):
        """Create pyproject.toml for uv"""
        try:
            # Format dependencies as a proper list without extra quotes
            deps_formatted = ",\n    ".join(dependencies)
            
            # Format dev dependencies
            dev_deps_formatted = ",\n    ".join([f'"{dep}"' for dep in DEV_DEPENDENCIES])
            
            # Format build system requires
            build_requires = ", ".join([f'"{req}"' for req in BUILD_SYSTEM["requires"]])
            
            content = f'''[project]
name = "{self.project_name}"
version = "0.1.0"
description = "A Python project generated by project-generator"
readme = "README.md"
requires-python = "{PYTHON_VERSION}"
dependencies = [
    {deps_formatted}
]

[build-system]
requires = [{build_requires}]
build-backend = "{BUILD_SYSTEM["build_backend"]}"

[tool.hatch.build.targets.wheel]
packages = ["src"]

[dependency-groups]
dev = [
    {dev_deps_formatted}
]
'''
            with open(self.project_path / "pyproject.toml", "w") as f:
                f.write(content)
        except (OSError, PermissionError) as e:
            raise RuntimeError(f"Failed to create pyproject.toml: {e}") from e
    
    def create_gitignore(self):
        """Create .gitignore file"""
        try:
            content = '''# Python
__pycache__/
*.py[cod]
*$py.class
*.so
.Python
env/
venv/
.venv/
ENV/
build/
develop-eggs/
dist/
downloads/
eggs/
.eggs/
lib/
lib64/
parts/
sdist/
var/
wheels/
*.egg-info/
.installed.cfg
*.egg

# Testing
.pytest_cache/
.coverage
htmlcov/

# IDEs
.vscode/
.idea/
*.swp
*.swo
*~

# Data
data/raw/*
data/processed/*
!data/raw/.gitkeep
!data/processed/.gitkeep

# Notebooks
.ipynb_checkpoints/

# Environment
.env
.env.local

# OS
.DS_Store
Thumbs.db
'''
            with open(self.project_path / ".gitignore", "w") as f:
                f.write(content)
        except (OSError, PermissionError) as e:
            raise RuntimeError(f"Failed to create .gitignore: {e}") from e
    
    def create_readme(self, content: str):
        """Create README.md"""
        try:
            with open(self.project_path / "README.md", "w") as f:
                f.write(content)
        except (OSError, PermissionError) as e:
            raise RuntimeError(f"Failed to create README.md: {e}") from e
    
    def create_basic_test(self):
        """Create a basic test file"""
        try:
            content = '''"""Basic tests for the project"""
import pytest


def test_project_structure():
    """Test that project structure is correct"""
    import os
    from pathlib import Path
    
    project_root = Path(__file__).parent.parent
    expected_dirs = ["notebooks", "artifacts", "reports", "research", "quality", "scripts", "data"]
    
    for dir_name in expected_dirs:
        assert (project_root / dir_name).exists(), f"Missing directory: {dir_name}"


def test_placeholder():
    """Placeholder test"""
    assert True
'''
            with open(self.project_path / "tests" / "test_basic.py", "w") as f:
                f.write(content)
            
            # Create __init__.py
            (self.project_path / "tests" / "__init__.py").touch()
        except (OSError, PermissionError) as e:
            raise RuntimeError(f"Failed to create test files: {e}") from e
    
    def create_src_init(self):
        """Create src/__init__.py to make it a proper package"""
        try:
            (self.project_path / "src" / "__init__.py").write_text(
                f'"""{self.project_name} package."""\n'
            )
        except (OSError, PermissionError) as e:
            raise RuntimeError(f"Failed to create src/__init__.py: {e}") from e
    
    def generate(self):
        """Generate the project (to be implemented by subclasses)"""
        raise NotImplementedError("Subclasses must implement generate()")

